"""
Dummy mutual fund data with all required metrics for portfolio optimization.
5 years of historical returns, at least 10 funds per category.
"""
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def generate_dummy_funds():
    """
    Generate dummy mutual fund data for both INR and USD currencies.
    Returns a DataFrame with all required metrics.
    5 years of historical data (1260 trading days).
    At least 10 funds per category.
    """
    funds = []
    
    # Generate dates for historical returns (252 trading days per year, 5 years = 1260 days)
    dates = pd.date_range(end=datetime.now(), periods=1260, freq='B')
    
    # INR Funds - At least 10 per category
    inr_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "HDFC Top 100 Fund", "type": "equity", "currency": "INR", "geography": "India", 
         "market_cap": "large", "volatility": 18.5, "returns": 14.2, "category": "large_cap"},
        {"name": "ICICI Prudential Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 17.8, "returns": 13.9, "category": "large_cap"},
        {"name": "SBI Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 19.2, "returns": 14.5, "category": "large_cap"},
        {"name": "Axis Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.0, "returns": 14.0, "category": "large_cap"},
        {"name": "Kotak Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.3, "returns": 14.1, "category": "large_cap"},
        {"name": "Franklin India Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 17.5, "returns": 13.7, "category": "large_cap"},
        {"name": "UTI Equity Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.7, "returns": 14.3, "category": "large_cap"},
        {"name": "DSP Top 100 Equity Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 19.0, "returns": 14.4, "category": "large_cap"},
        {"name": "Aditya Birla Sun Life Frontline Equity Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.2, "returns": 13.8, "category": "large_cap"},
        {"name": "Mirae Asset Large Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.8, "returns": 14.2, "category": "large_cap"},
        {"name": "Nippon India Large Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.4, "returns": 14.0, "category": "large_cap"},
        {"name": "Tata Large Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "large", "volatility": 18.6, "returns": 14.1, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "HDFC Mid-Cap Opportunities Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.5, "returns": 16.8, "category": "mid_cap"},
        {"name": "SBI Magnum Midcap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 23.1, "returns": 17.2, "category": "mid_cap"},
        {"name": "Kotak Emerging Equity Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 21.8, "returns": 16.5, "category": "mid_cap"},
        {"name": "DSP Midcap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.9, "returns": 17.0, "category": "mid_cap"},
        {"name": "ICICI Prudential Midcap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.2, "returns": 16.6, "category": "mid_cap"},
        {"name": "Axis Midcap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.7, "returns": 16.9, "category": "mid_cap"},
        {"name": "Franklin India Prima Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 21.5, "returns": 16.3, "category": "mid_cap"},
        {"name": "UTI Mid Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.4, "returns": 16.7, "category": "mid_cap"},
        {"name": "Aditya Birla Sun Life Mid Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.0, "returns": 16.4, "category": "mid_cap"},
        {"name": "Mirae Asset Emerging Bluechip Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 23.0, "returns": 17.1, "category": "mid_cap"},
        {"name": "Nippon India Growth Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "mid", "volatility": 22.6, "returns": 16.8, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Nippon India Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.5, "returns": 19.5, "category": "small_cap"},
        {"name": "HDFC Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 29.2, "returns": 20.1, "category": "small_cap"},
        {"name": "SBI Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 27.8, "returns": 19.0, "category": "small_cap"},
        {"name": "Axis Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.9, "returns": 19.8, "category": "small_cap"},
        {"name": "Kotak Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.2, "returns": 19.3, "category": "small_cap"},
        {"name": "ICICI Prudential Smallcap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 29.0, "returns": 19.9, "category": "small_cap"},
        {"name": "DSP Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.7, "returns": 19.6, "category": "small_cap"},
        {"name": "Franklin India Smaller Companies Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 27.5, "returns": 18.8, "category": "small_cap"},
        {"name": "UTI Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.4, "returns": 19.2, "category": "small_cap"},
        {"name": "Aditya Birla Sun Life Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.8, "returns": 19.7, "category": "small_cap"},
        {"name": "Mirae Asset Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 29.1, "returns": 20.0, "category": "small_cap"},
        {"name": "Tata Small Cap Fund", "type": "equity", "currency": "INR", "geography": "India",
         "market_cap": "small", "volatility": 28.6, "returns": 19.4, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "HDFC Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.2, "returns": 7.5, "category": "debt"},
        {"name": "ICICI Prudential Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.5, "returns": 7.8, "category": "debt"},
        {"name": "SBI Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.0, "returns": 7.3, "category": "debt"},
        {"name": "Axis Corporate Debt Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.3, "returns": 7.6, "category": "debt"},
        {"name": "Kotak Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.1, "returns": 7.4, "category": "debt"},
        {"name": "Franklin India Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.4, "returns": 7.7, "category": "debt"},
        {"name": "UTI Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.2, "returns": 7.5, "category": "debt"},
        {"name": "DSP Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.3, "returns": 7.6, "category": "debt"},
        {"name": "Aditya Birla Sun Life Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.1, "returns": 7.4, "category": "debt"},
        {"name": "Mirae Asset Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.4, "returns": 7.7, "category": "debt"},
        {"name": "Nippon India Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.2, "returns": 7.5, "category": "debt"},
        {"name": "Tata Corporate Bond Fund", "type": "debt", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 4.3, "returns": 7.6, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "HDFC Balanced Advantage Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.5, "returns": 11.8, "category": "balanced"},
        {"name": "ICICI Prudential Balanced Advantage Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 13.0, "returns": 12.0, "category": "balanced"},
        {"name": "SBI Balanced Advantage Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.8, "returns": 11.9, "category": "balanced"},
        {"name": "Axis Balanced Advantage Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.6, "returns": 11.7, "category": "balanced"},
        {"name": "Kotak Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.7, "returns": 11.8, "category": "balanced"},
        {"name": "Franklin India Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.4, "returns": 11.6, "category": "balanced"},
        {"name": "UTI Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.9, "returns": 12.0, "category": "balanced"},
        {"name": "DSP Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.5, "returns": 11.7, "category": "balanced"},
        {"name": "Aditya Birla Sun Life Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.6, "returns": 11.8, "category": "balanced"},
        {"name": "Mirae Asset Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.8, "returns": 11.9, "category": "balanced"},
        {"name": "Nippon India Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.7, "returns": 11.8, "category": "balanced"},
        {"name": "Tata Balanced Fund", "type": "balanced", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 12.5, "returns": 11.7, "category": "balanced"},
        
        # Tax Saver (ELSS) Funds (10+ funds)
        {"name": "HDFC TaxSaver Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.5, "returns": 15.5, "category": "tax_saver"},
        {"name": "ICICI Prudential Tax Plan", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 21.0, "returns": 15.8, "category": "tax_saver"},
        {"name": "SBI Long Term Equity Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.8, "returns": 15.6, "category": "tax_saver"},
        {"name": "Axis Long Term Equity Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.3, "returns": 15.4, "category": "tax_saver"},
        {"name": "Kotak Tax Saver Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.6, "returns": 15.5, "category": "tax_saver"},
        {"name": "Franklin India Taxshield Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.4, "returns": 15.4, "category": "tax_saver"},
        {"name": "UTI Long Term Equity Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.7, "returns": 15.6, "category": "tax_saver"},
        {"name": "DSP Tax Saver Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.5, "returns": 15.5, "category": "tax_saver"},
        {"name": "Aditya Birla Sun Life Tax Relief 96", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.9, "returns": 15.7, "category": "tax_saver"},
        {"name": "Mirae Asset Tax Saver Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 21.1, "returns": 15.9, "category": "tax_saver"},
        {"name": "Nippon India Tax Saver Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.6, "returns": 15.5, "category": "tax_saver"},
        {"name": "Tata Tax Saving Fund", "type": "taxsaver", "currency": "INR", "geography": "India",
         "market_cap": None, "volatility": 20.8, "returns": 15.6, "category": "tax_saver"},
    ]
    
    # USD Funds - USA (10+ per category)
    usd_usa_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Vanguard S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.5, "returns": 12.5, "category": "large_cap"},
        {"name": "Fidelity 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.8, "returns": 12.7, "category": "large_cap"},
        {"name": "Schwab Total Stock Market Index", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 17.0, "returns": 12.6, "category": "large_cap"},
        {"name": "T. Rowe Price Equity Index 500 Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.6, "returns": 12.6, "category": "large_cap"},
        {"name": "BlackRock S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.7, "returns": 12.6, "category": "large_cap"},
        {"name": "State Street S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.9, "returns": 12.8, "category": "large_cap"},
        {"name": "Invesco S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.4, "returns": 12.5, "category": "large_cap"},
        {"name": "Northern Trust S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.7, "returns": 12.7, "category": "large_cap"},
        {"name": "JPMorgan Equity Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.8, "returns": 12.7, "category": "large_cap"},
        {"name": "Goldman Sachs S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.6, "returns": 12.6, "category": "large_cap"},
        {"name": "Morgan Stanley S&P 500 Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 16.9, "returns": 12.8, "category": "large_cap"},
        {"name": "American Funds Growth Fund of America", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "large", "volatility": 17.2, "returns": 13.0, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Vanguard Mid-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.5, "returns": 14.2, "category": "mid_cap"},
        {"name": "Fidelity Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.8, "returns": 14.4, "category": "mid_cap"},
        {"name": "Schwab Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.6, "returns": 14.3, "category": "mid_cap"},
        {"name": "T. Rowe Price Mid-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.7, "returns": 14.3, "category": "mid_cap"},
        {"name": "BlackRock Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.4, "returns": 14.2, "category": "mid_cap"},
        {"name": "State Street Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.9, "returns": 14.5, "category": "mid_cap"},
        {"name": "Invesco Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.3, "returns": 14.1, "category": "mid_cap"},
        {"name": "Northern Trust Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.6, "returns": 14.3, "category": "mid_cap"},
        {"name": "JPMorgan Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.7, "returns": 14.4, "category": "mid_cap"},
        {"name": "Goldman Sachs Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.5, "returns": 14.2, "category": "mid_cap"},
        {"name": "Morgan Stanley Mid Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "mid", "volatility": 19.8, "returns": 14.4, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Vanguard Small-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.5, "returns": 16.8, "category": "small_cap"},
        {"name": "Fidelity Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.8, "returns": 17.0, "category": "small_cap"},
        {"name": "Schwab Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.6, "returns": 16.9, "category": "small_cap"},
        {"name": "T. Rowe Price Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.7, "returns": 16.9, "category": "small_cap"},
        {"name": "BlackRock Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.4, "returns": 16.8, "category": "small_cap"},
        {"name": "State Street Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.9, "returns": 17.1, "category": "small_cap"},
        {"name": "Invesco Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.3, "returns": 16.7, "category": "small_cap"},
        {"name": "Northern Trust Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.6, "returns": 16.9, "category": "small_cap"},
        {"name": "JPMorgan Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.7, "returns": 17.0, "category": "small_cap"},
        {"name": "Goldman Sachs Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.5, "returns": 16.8, "category": "small_cap"},
        {"name": "Morgan Stanley Small Cap Index Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 24.8, "returns": 17.0, "category": "small_cap"},
        {"name": "American Funds Small Cap World Fund", "type": "equity", "currency": "USD", "geography": "USA",
         "market_cap": "small", "volatility": 25.0, "returns": 17.2, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Vanguard Total Bond Market Index", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.5, "returns": 4.2, "category": "debt"},
        {"name": "Fidelity U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.6, "returns": 4.3, "category": "debt"},
        {"name": "Schwab U.S. Aggregate Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.4, "returns": 4.1, "category": "debt"},
        {"name": "T. Rowe Price U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.5, "returns": 4.2, "category": "debt"},
        {"name": "BlackRock U.S. Aggregate Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.6, "returns": 4.3, "category": "debt"},
        {"name": "State Street U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.4, "returns": 4.1, "category": "debt"},
        {"name": "Invesco U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.5, "returns": 4.2, "category": "debt"},
        {"name": "Northern Trust U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.6, "returns": 4.3, "category": "debt"},
        {"name": "JPMorgan U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.5, "returns": 4.2, "category": "debt"},
        {"name": "Goldman Sachs U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.4, "returns": 4.1, "category": "debt"},
        {"name": "Morgan Stanley U.S. Bond Index Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.6, "returns": 4.3, "category": "debt"},
        {"name": "PIMCO Total Return Fund", "type": "debt", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 3.7, "returns": 4.4, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Vanguard Balanced Index Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.5, "returns": 9.5, "category": "balanced"},
        {"name": "Fidelity Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.8, "returns": 9.7, "category": "balanced"},
        {"name": "Schwab Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.6, "returns": 9.6, "category": "balanced"},
        {"name": "T. Rowe Price Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.7, "returns": 9.6, "category": "balanced"},
        {"name": "BlackRock Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.5, "returns": 9.5, "category": "balanced"},
        {"name": "State Street Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.8, "returns": 9.7, "category": "balanced"},
        {"name": "Invesco Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.6, "returns": 9.6, "category": "balanced"},
        {"name": "Northern Trust Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.7, "returns": 9.6, "category": "balanced"},
        {"name": "JPMorgan Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.5, "returns": 9.5, "category": "balanced"},
        {"name": "Goldman Sachs Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.8, "returns": 9.7, "category": "balanced"},
        {"name": "Morgan Stanley Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.6, "returns": 9.6, "category": "balanced"},
        {"name": "American Funds Balanced Fund", "type": "balanced", "currency": "USD", "geography": "USA",
         "market_cap": None, "volatility": 10.9, "returns": 9.8, "category": "balanced"},
    ]
    
    # USD Funds - Japan (10+ per category)
    usd_japan_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Nikko AM Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.5, "returns": 8.5, "category": "large_cap"},
        {"name": "Nomura Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.8, "returns": 8.7, "category": "large_cap"},
        {"name": "Daiwa Japan Large Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.6, "returns": 8.6, "category": "large_cap"},
        {"name": "Mitsubishi UFJ Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.7, "returns": 8.6, "category": "large_cap"},
        {"name": "Sumitomo Mitsui Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.4, "returns": 8.5, "category": "large_cap"},
        {"name": "Mizuho Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.9, "returns": 8.8, "category": "large_cap"},
        {"name": "SMBC Nikko Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.5, "returns": 8.5, "category": "large_cap"},
        {"name": "Rakuten Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.6, "returns": 8.6, "category": "large_cap"},
        {"name": "SBI Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.7, "returns": 8.7, "category": "large_cap"},
        {"name": "Resona Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.8, "returns": 8.7, "category": "large_cap"},
        {"name": "Shinsei Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.4, "returns": 8.5, "category": "large_cap"},
        {"name": "Aozora Japan Equity Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "large", "volatility": 18.6, "returns": 8.6, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Daiwa Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.5, "returns": 10.2, "category": "mid_cap"},
        {"name": "Nikko AM Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.6, "returns": 10.3, "category": "mid_cap"},
        {"name": "Nomura Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.4, "returns": 10.1, "category": "mid_cap"},
        {"name": "Mitsubishi UFJ Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.7, "returns": 10.4, "category": "mid_cap"},
        {"name": "Sumitomo Mitsui Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.3, "returns": 10.0, "category": "mid_cap"},
        {"name": "Mizuho Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.8, "returns": 10.5, "category": "mid_cap"},
        {"name": "SMBC Nikko Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.5, "returns": 10.2, "category": "mid_cap"},
        {"name": "Rakuten Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.6, "returns": 10.3, "category": "mid_cap"},
        {"name": "SBI Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.7, "returns": 10.4, "category": "mid_cap"},
        {"name": "Resona Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.4, "returns": 10.1, "category": "mid_cap"},
        {"name": "Shinsei Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.3, "returns": 10.0, "category": "mid_cap"},
        {"name": "Aozora Japan Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "mid", "volatility": 21.6, "returns": 10.3, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Daiwa Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.5, "returns": 12.2, "category": "small_cap"},
        {"name": "Nikko AM Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.6, "returns": 12.3, "category": "small_cap"},
        {"name": "Nomura Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.4, "returns": 12.1, "category": "small_cap"},
        {"name": "Mitsubishi UFJ Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.7, "returns": 12.4, "category": "small_cap"},
        {"name": "Sumitomo Mitsui Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.3, "returns": 12.0, "category": "small_cap"},
        {"name": "Mizuho Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.8, "returns": 12.5, "category": "small_cap"},
        {"name": "SMBC Nikko Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.5, "returns": 12.2, "category": "small_cap"},
        {"name": "Rakuten Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.6, "returns": 12.3, "category": "small_cap"},
        {"name": "SBI Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.7, "returns": 12.4, "category": "small_cap"},
        {"name": "Resona Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.4, "returns": 12.1, "category": "small_cap"},
        {"name": "Shinsei Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.3, "returns": 12.0, "category": "small_cap"},
        {"name": "Aozora Japan Small Cap Fund", "type": "equity", "currency": "USD", "geography": "Japan",
         "market_cap": "small", "volatility": 25.6, "returns": 12.3, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Nomura Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.8, "returns": 1.5, "category": "debt"},
        {"name": "Daiwa Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.7, "returns": 1.4, "category": "debt"},
        {"name": "Nikko AM Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.9, "returns": 1.6, "category": "debt"},
        {"name": "Mitsubishi UFJ Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.8, "returns": 1.5, "category": "debt"},
        {"name": "Sumitomo Mitsui Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.7, "returns": 1.4, "category": "debt"},
        {"name": "Mizuho Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.9, "returns": 1.6, "category": "debt"},
        {"name": "SMBC Nikko Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.8, "returns": 1.5, "category": "debt"},
        {"name": "Rakuten Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.7, "returns": 1.4, "category": "debt"},
        {"name": "SBI Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.9, "returns": 1.6, "category": "debt"},
        {"name": "Resona Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.8, "returns": 1.5, "category": "debt"},
        {"name": "Shinsei Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.7, "returns": 1.4, "category": "debt"},
        {"name": "Aozora Japan Bond Fund", "type": "debt", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 2.8, "returns": 1.5, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Mitsubishi Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.5, "returns": 6.5, "category": "balanced"},
        {"name": "Nikko AM Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.6, "returns": 6.6, "category": "balanced"},
        {"name": "Nomura Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.4, "returns": 6.4, "category": "balanced"},
        {"name": "Daiwa Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.7, "returns": 6.7, "category": "balanced"},
        {"name": "Sumitomo Mitsui Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.3, "returns": 6.3, "category": "balanced"},
        {"name": "Mizuho Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.8, "returns": 6.8, "category": "balanced"},
        {"name": "SMBC Nikko Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.5, "returns": 6.5, "category": "balanced"},
        {"name": "Rakuten Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.6, "returns": 6.6, "category": "balanced"},
        {"name": "SBI Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.7, "returns": 6.7, "category": "balanced"},
        {"name": "Resona Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.4, "returns": 6.4, "category": "balanced"},
        {"name": "Shinsei Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.3, "returns": 6.3, "category": "balanced"},
        {"name": "Aozora Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Japan",
         "market_cap": None, "volatility": 11.6, "returns": 6.6, "category": "balanced"},
    ]
    
    # USD Funds - India (for USD investors) (10+ per category)
    usd_india_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Franklin India Bluechip Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.5, "returns": 13.5, "category": "large_cap"},
        {"name": "Templeton India Growth Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.8, "returns": 13.7, "category": "large_cap"},
        {"name": "HSBC India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.6, "returns": 13.6, "category": "large_cap"},
        {"name": "JP Morgan India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.7, "returns": 13.6, "category": "large_cap"},
        {"name": "Fidelity India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.4, "returns": 13.4, "category": "large_cap"},
        {"name": "BlackRock India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.8, "returns": 13.7, "category": "large_cap"},
        {"name": "Goldman Sachs India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.5, "returns": 13.5, "category": "large_cap"},
        {"name": "Morgan Stanley India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.6, "returns": 13.6, "category": "large_cap"},
        {"name": "UBS India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.7, "returns": 13.6, "category": "large_cap"},
        {"name": "Deutsche India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.4, "returns": 13.4, "category": "large_cap"},
        {"name": "Credit Suisse India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.8, "returns": 13.7, "category": "large_cap"},
        {"name": "Barclays India Equity Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "large", "volatility": 19.5, "returns": 13.5, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Franklin India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.5, "returns": 16.2, "category": "mid_cap"},
        {"name": "Templeton India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.6, "returns": 16.3, "category": "mid_cap"},
        {"name": "HSBC India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.4, "returns": 16.1, "category": "mid_cap"},
        {"name": "JP Morgan India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.7, "returns": 16.4, "category": "mid_cap"},
        {"name": "Fidelity India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.3, "returns": 16.0, "category": "mid_cap"},
        {"name": "BlackRock India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.8, "returns": 16.5, "category": "mid_cap"},
        {"name": "Goldman Sachs India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.5, "returns": 16.2, "category": "mid_cap"},
        {"name": "Morgan Stanley India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.6, "returns": 16.3, "category": "mid_cap"},
        {"name": "UBS India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.7, "returns": 16.4, "category": "mid_cap"},
        {"name": "Deutsche India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.4, "returns": 16.1, "category": "mid_cap"},
        {"name": "Credit Suisse India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.8, "returns": 16.5, "category": "mid_cap"},
        {"name": "Barclays India Mid-Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "mid", "volatility": 23.5, "returns": 16.2, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Franklin India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.5, "returns": 18.8, "category": "small_cap"},
        {"name": "Templeton India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.6, "returns": 18.9, "category": "small_cap"},
        {"name": "HSBC India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.4, "returns": 18.7, "category": "small_cap"},
        {"name": "JP Morgan India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.7, "returns": 19.0, "category": "small_cap"},
        {"name": "Fidelity India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.3, "returns": 18.6, "category": "small_cap"},
        {"name": "BlackRock India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.8, "returns": 19.1, "category": "small_cap"},
        {"name": "Goldman Sachs India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.5, "returns": 18.8, "category": "small_cap"},
        {"name": "Morgan Stanley India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.6, "returns": 18.9, "category": "small_cap"},
        {"name": "UBS India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.7, "returns": 19.0, "category": "small_cap"},
        {"name": "Deutsche India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.4, "returns": 18.7, "category": "small_cap"},
        {"name": "Credit Suisse India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.8, "returns": 19.1, "category": "small_cap"},
        {"name": "Barclays India Small Cap Fund (USD)", "type": "equity", "currency": "USD", "geography": "India",
         "market_cap": "small", "volatility": 27.5, "returns": 18.8, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Franklin India Corporate Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.5, "returns": 7.2, "category": "debt"},
        {"name": "Templeton India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.6, "returns": 7.3, "category": "debt"},
        {"name": "HSBC India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.4, "returns": 7.1, "category": "debt"},
        {"name": "JP Morgan India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.7, "returns": 7.4, "category": "debt"},
        {"name": "Fidelity India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.3, "returns": 7.0, "category": "debt"},
        {"name": "BlackRock India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.8, "returns": 7.5, "category": "debt"},
        {"name": "Goldman Sachs India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.5, "returns": 7.2, "category": "debt"},
        {"name": "Morgan Stanley India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.6, "returns": 7.3, "category": "debt"},
        {"name": "UBS India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.7, "returns": 7.4, "category": "debt"},
        {"name": "Deutsche India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.4, "returns": 7.1, "category": "debt"},
        {"name": "Credit Suisse India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.8, "returns": 7.5, "category": "debt"},
        {"name": "Barclays India Bond Fund (USD)", "type": "debt", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 4.5, "returns": 7.2, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Templeton India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.5, "returns": 11.5, "category": "balanced"},
        {"name": "Franklin India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.6, "returns": 11.6, "category": "balanced"},
        {"name": "HSBC India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.4, "returns": 11.4, "category": "balanced"},
        {"name": "JP Morgan India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.7, "returns": 11.7, "category": "balanced"},
        {"name": "Fidelity India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.3, "returns": 11.3, "category": "balanced"},
        {"name": "BlackRock India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.8, "returns": 11.8, "category": "balanced"},
        {"name": "Goldman Sachs India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.5, "returns": 11.5, "category": "balanced"},
        {"name": "Morgan Stanley India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.6, "returns": 11.6, "category": "balanced"},
        {"name": "UBS India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.7, "returns": 11.7, "category": "balanced"},
        {"name": "Deutsche India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.4, "returns": 11.4, "category": "balanced"},
        {"name": "Credit Suisse India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.8, "returns": 11.8, "category": "balanced"},
        {"name": "Barclays India Balanced Fund (USD)", "type": "balanced", "currency": "USD", "geography": "India",
         "market_cap": None, "volatility": 13.5, "returns": 11.5, "category": "balanced"},
    ]
    
    # USD Funds - Europe (10+ per category)
    usd_europe_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Vanguard European Stock Index Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.5, "returns": 10.5, "category": "large_cap"},
        {"name": "Fidelity European Index Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.8, "returns": 10.7, "category": "large_cap"},
        {"name": "BlackRock European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.6, "returns": 10.6, "category": "large_cap"},
        {"name": "Allianz European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.4, "returns": 10.4, "category": "large_cap"},
        {"name": "Deutsche European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.7, "returns": 10.6, "category": "large_cap"},
        {"name": "BNP Paribas European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.5, "returns": 10.5, "category": "large_cap"},
        {"name": "Societe Generale European Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.6, "returns": 10.6, "category": "large_cap"},
        {"name": "Credit Agricole European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.8, "returns": 10.8, "category": "large_cap"},
        {"name": "ING European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.4, "returns": 10.4, "category": "large_cap"},
        {"name": "UBS European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.7, "returns": 10.7, "category": "large_cap"},
        {"name": "Credit Suisse European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.5, "returns": 10.5, "category": "large_cap"},
        {"name": "AXA European Equity Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "large", "volatility": 17.6, "returns": 10.6, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Vanguard European Mid-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.5, "returns": 12.2, "category": "mid_cap"},
        {"name": "Fidelity European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.8, "returns": 12.4, "category": "mid_cap"},
        {"name": "BlackRock European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.6, "returns": 12.3, "category": "mid_cap"},
        {"name": "Allianz European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.4, "returns": 12.1, "category": "mid_cap"},
        {"name": "Deutsche European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.7, "returns": 12.3, "category": "mid_cap"},
        {"name": "BNP Paribas European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.5, "returns": 12.2, "category": "mid_cap"},
        {"name": "Societe Generale European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.6, "returns": 12.3, "category": "mid_cap"},
        {"name": "Credit Agricole European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.8, "returns": 12.4, "category": "mid_cap"},
        {"name": "ING European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.4, "returns": 12.1, "category": "mid_cap"},
        {"name": "UBS European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.7, "returns": 12.3, "category": "mid_cap"},
        {"name": "Credit Suisse European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.5, "returns": 12.2, "category": "mid_cap"},
        {"name": "AXA European Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "mid", "volatility": 20.6, "returns": 12.3, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Vanguard European Small-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.5, "returns": 14.8, "category": "small_cap"},
        {"name": "Fidelity European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.8, "returns": 15.0, "category": "small_cap"},
        {"name": "BlackRock European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.6, "returns": 14.9, "category": "small_cap"},
        {"name": "Allianz European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.4, "returns": 14.7, "category": "small_cap"},
        {"name": "Deutsche European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.7, "returns": 14.9, "category": "small_cap"},
        {"name": "BNP Paribas European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.5, "returns": 14.8, "category": "small_cap"},
        {"name": "Societe Generale European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.6, "returns": 14.9, "category": "small_cap"},
        {"name": "Credit Agricole European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.8, "returns": 15.0, "category": "small_cap"},
        {"name": "ING European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.4, "returns": 14.7, "category": "small_cap"},
        {"name": "UBS European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.7, "returns": 14.9, "category": "small_cap"},
        {"name": "Credit Suisse European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.5, "returns": 14.8, "category": "small_cap"},
        {"name": "AXA European Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "Europe",
         "market_cap": "small", "volatility": 25.6, "returns": 14.9, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Vanguard European Bond Index Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.2, "returns": 3.5, "category": "debt"},
        {"name": "Fidelity European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.3, "returns": 3.6, "category": "debt"},
        {"name": "BlackRock European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.1, "returns": 3.4, "category": "debt"},
        {"name": "Allianz European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.2, "returns": 3.5, "category": "debt"},
        {"name": "Deutsche European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.3, "returns": 3.6, "category": "debt"},
        {"name": "BNP Paribas European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.1, "returns": 3.4, "category": "debt"},
        {"name": "Societe Generale European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.2, "returns": 3.5, "category": "debt"},
        {"name": "Credit Agricole European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.3, "returns": 3.6, "category": "debt"},
        {"name": "ING European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.1, "returns": 3.4, "category": "debt"},
        {"name": "UBS European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.2, "returns": 3.5, "category": "debt"},
        {"name": "Credit Suisse European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.3, "returns": 3.6, "category": "debt"},
        {"name": "AXA European Bond Fund", "type": "debt", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 3.2, "returns": 3.5, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Vanguard European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.2, "returns": 8.5, "category": "balanced"},
        {"name": "Fidelity European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.5, "returns": 8.7, "category": "balanced"},
        {"name": "BlackRock European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.3, "returns": 8.6, "category": "balanced"},
        {"name": "Allianz European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.1, "returns": 8.4, "category": "balanced"},
        {"name": "Deutsche European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.4, "returns": 8.6, "category": "balanced"},
        {"name": "BNP Paribas European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.2, "returns": 8.5, "category": "balanced"},
        {"name": "Societe Generale European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.3, "returns": 8.6, "category": "balanced"},
        {"name": "Credit Agricole European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.5, "returns": 8.7, "category": "balanced"},
        {"name": "ING European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.1, "returns": 8.4, "category": "balanced"},
        {"name": "UBS European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.4, "returns": 8.6, "category": "balanced"},
        {"name": "Credit Suisse European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.2, "returns": 8.5, "category": "balanced"},
        {"name": "AXA European Balanced Fund", "type": "balanced", "currency": "USD", "geography": "Europe",
         "market_cap": None, "volatility": 10.3, "returns": 8.6, "category": "balanced"},
    ]
    
    # USD Funds - UK (10+ per category)
    usd_uk_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Vanguard FTSE 100 Index Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.8, "returns": 9.5, "category": "large_cap"},
        {"name": "Fidelity UK Equity Index Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 17.0, "returns": 9.7, "category": "large_cap"},
        {"name": "BlackRock UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.9, "returns": 9.6, "category": "large_cap"},
        {"name": "HSBC UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.7, "returns": 9.4, "category": "large_cap"},
        {"name": "Barclays UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 17.1, "returns": 9.8, "category": "large_cap"},
        {"name": "Lloyds UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.8, "returns": 9.5, "category": "large_cap"},
        {"name": "NatWest UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.9, "returns": 9.6, "category": "large_cap"},
        {"name": "Standard Chartered UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 17.0, "returns": 9.7, "category": "large_cap"},
        {"name": "Schroders UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.8, "returns": 9.5, "category": "large_cap"},
        {"name": "Legal & General UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.9, "returns": 9.6, "category": "large_cap"},
        {"name": "Aviva UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 17.0, "returns": 9.7, "category": "large_cap"},
        {"name": "Prudential UK Equity Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "large", "volatility": 16.8, "returns": 9.5, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Vanguard UK Mid-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.8, "returns": 11.2, "category": "mid_cap"},
        {"name": "Fidelity UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 20.0, "returns": 11.4, "category": "mid_cap"},
        {"name": "BlackRock UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.9, "returns": 11.3, "category": "mid_cap"},
        {"name": "HSBC UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.7, "returns": 11.1, "category": "mid_cap"},
        {"name": "Barclays UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 20.1, "returns": 11.5, "category": "mid_cap"},
        {"name": "Lloyds UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.8, "returns": 11.2, "category": "mid_cap"},
        {"name": "NatWest UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.9, "returns": 11.3, "category": "mid_cap"},
        {"name": "Standard Chartered UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 20.0, "returns": 11.4, "category": "mid_cap"},
        {"name": "Schroders UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.8, "returns": 11.2, "category": "mid_cap"},
        {"name": "Legal & General UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.9, "returns": 11.3, "category": "mid_cap"},
        {"name": "Aviva UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 20.0, "returns": 11.4, "category": "mid_cap"},
        {"name": "Prudential UK Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "mid", "volatility": 19.8, "returns": 11.2, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Vanguard UK Small-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.8, "returns": 13.8, "category": "small_cap"},
        {"name": "Fidelity UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 25.0, "returns": 14.0, "category": "small_cap"},
        {"name": "BlackRock UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.9, "returns": 13.9, "category": "small_cap"},
        {"name": "HSBC UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.7, "returns": 13.7, "category": "small_cap"},
        {"name": "Barclays UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 25.1, "returns": 14.1, "category": "small_cap"},
        {"name": "Lloyds UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.8, "returns": 13.8, "category": "small_cap"},
        {"name": "NatWest UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.9, "returns": 13.9, "category": "small_cap"},
        {"name": "Standard Chartered UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 25.0, "returns": 14.0, "category": "small_cap"},
        {"name": "Schroders UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.8, "returns": 13.8, "category": "small_cap"},
        {"name": "Legal & General UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.9, "returns": 13.9, "category": "small_cap"},
        {"name": "Aviva UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 25.0, "returns": 14.0, "category": "small_cap"},
        {"name": "Prudential UK Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "UK",
         "market_cap": "small", "volatility": 24.8, "returns": 13.8, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Vanguard UK Gilt Index Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.0, "returns": 3.2, "category": "debt"},
        {"name": "Fidelity UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.1, "returns": 3.3, "category": "debt"},
        {"name": "BlackRock UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 2.9, "returns": 3.1, "category": "debt"},
        {"name": "HSBC UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.0, "returns": 3.2, "category": "debt"},
        {"name": "Barclays UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.1, "returns": 3.3, "category": "debt"},
        {"name": "Lloyds UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.0, "returns": 3.2, "category": "debt"},
        {"name": "NatWest UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 2.9, "returns": 3.1, "category": "debt"},
        {"name": "Standard Chartered UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.1, "returns": 3.3, "category": "debt"},
        {"name": "Schroders UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.0, "returns": 3.2, "category": "debt"},
        {"name": "Legal & General UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.1, "returns": 3.3, "category": "debt"},
        {"name": "Aviva UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 3.0, "returns": 3.2, "category": "debt"},
        {"name": "Prudential UK Bond Fund", "type": "debt", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 2.9, "returns": 3.1, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Vanguard UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.0, "returns": 8.2, "category": "balanced"},
        {"name": "Fidelity UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.3, "returns": 8.4, "category": "balanced"},
        {"name": "BlackRock UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.1, "returns": 8.3, "category": "balanced"},
        {"name": "HSBC UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 9.9, "returns": 8.1, "category": "balanced"},
        {"name": "Barclays UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.2, "returns": 8.3, "category": "balanced"},
        {"name": "Lloyds UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.0, "returns": 8.2, "category": "balanced"},
        {"name": "NatWest UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.1, "returns": 8.3, "category": "balanced"},
        {"name": "Standard Chartered UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.3, "returns": 8.4, "category": "balanced"},
        {"name": "Schroders UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.0, "returns": 8.2, "category": "balanced"},
        {"name": "Legal & General UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.1, "returns": 8.3, "category": "balanced"},
        {"name": "Aviva UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.2, "returns": 8.3, "category": "balanced"},
        {"name": "Prudential UK Balanced Fund", "type": "balanced", "currency": "USD", "geography": "UK",
         "market_cap": None, "volatility": 10.0, "returns": 8.2, "category": "balanced"},
    ]
    
    # USD Funds - China (10+ per category)
    usd_china_funds = [
        # Large Cap Equity (10+ funds)
        {"name": "Vanguard China A-Share Index Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.5, "returns": 11.5, "category": "large_cap"},
        {"name": "Fidelity China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.8, "returns": 11.7, "category": "large_cap"},
        {"name": "BlackRock China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.6, "returns": 11.6, "category": "large_cap"},
        {"name": "HSBC China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.4, "returns": 11.4, "category": "large_cap"},
        {"name": "JP Morgan China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.7, "returns": 11.6, "category": "large_cap"},
        {"name": "Goldman Sachs China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.9, "returns": 11.8, "category": "large_cap"},
        {"name": "Morgan Stanley China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.5, "returns": 11.5, "category": "large_cap"},
        {"name": "UBS China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.6, "returns": 11.6, "category": "large_cap"},
        {"name": "Deutsche China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.4, "returns": 11.4, "category": "large_cap"},
        {"name": "Credit Suisse China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.8, "returns": 11.7, "category": "large_cap"},
        {"name": "Barclays China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.5, "returns": 11.5, "category": "large_cap"},
        {"name": "Standard Chartered China Equity Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "large", "volatility": 22.7, "returns": 11.6, "category": "large_cap"},
        
        # Mid Cap Equity (10+ funds)
        {"name": "Vanguard China Mid-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.5, "returns": 14.2, "category": "mid_cap"},
        {"name": "Fidelity China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.8, "returns": 14.4, "category": "mid_cap"},
        {"name": "BlackRock China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.6, "returns": 14.3, "category": "mid_cap"},
        {"name": "HSBC China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.4, "returns": 14.1, "category": "mid_cap"},
        {"name": "JP Morgan China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.7, "returns": 14.3, "category": "mid_cap"},
        {"name": "Goldman Sachs China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.9, "returns": 14.5, "category": "mid_cap"},
        {"name": "Morgan Stanley China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.5, "returns": 14.2, "category": "mid_cap"},
        {"name": "UBS China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.6, "returns": 14.3, "category": "mid_cap"},
        {"name": "Deutsche China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.4, "returns": 14.1, "category": "mid_cap"},
        {"name": "Credit Suisse China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.8, "returns": 14.4, "category": "mid_cap"},
        {"name": "Barclays China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.5, "returns": 14.2, "category": "mid_cap"},
        {"name": "Standard Chartered China Mid-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "mid", "volatility": 26.7, "returns": 14.3, "category": "mid_cap"},
        
        # Small Cap Equity (10+ funds)
        {"name": "Vanguard China Small-Cap Index Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.5, "returns": 16.8, "category": "small_cap"},
        {"name": "Fidelity China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.8, "returns": 17.0, "category": "small_cap"},
        {"name": "BlackRock China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.6, "returns": 16.9, "category": "small_cap"},
        {"name": "HSBC China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.4, "returns": 16.7, "category": "small_cap"},
        {"name": "JP Morgan China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.7, "returns": 16.9, "category": "small_cap"},
        {"name": "Goldman Sachs China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.9, "returns": 17.1, "category": "small_cap"},
        {"name": "Morgan Stanley China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.5, "returns": 16.8, "category": "small_cap"},
        {"name": "UBS China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.6, "returns": 16.9, "category": "small_cap"},
        {"name": "Deutsche China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.4, "returns": 16.7, "category": "small_cap"},
        {"name": "Credit Suisse China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.8, "returns": 17.0, "category": "small_cap"},
        {"name": "Barclays China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.5, "returns": 16.8, "category": "small_cap"},
        {"name": "Standard Chartered China Small-Cap Fund", "type": "equity", "currency": "USD", "geography": "China",
         "market_cap": "small", "volatility": 30.7, "returns": 16.9, "category": "small_cap"},
        
        # Debt Funds (10+ funds)
        {"name": "Vanguard China Bond Index Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.2, "returns": 5.5, "category": "debt"},
        {"name": "Fidelity China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.3, "returns": 5.6, "category": "debt"},
        {"name": "BlackRock China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.1, "returns": 5.4, "category": "debt"},
        {"name": "HSBC China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.2, "returns": 5.5, "category": "debt"},
        {"name": "JP Morgan China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.3, "returns": 5.6, "category": "debt"},
        {"name": "Goldman Sachs China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.4, "returns": 5.7, "category": "debt"},
        {"name": "Morgan Stanley China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.2, "returns": 5.5, "category": "debt"},
        {"name": "UBS China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.3, "returns": 5.6, "category": "debt"},
        {"name": "Deutsche China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.1, "returns": 5.4, "category": "debt"},
        {"name": "Credit Suisse China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.4, "returns": 5.7, "category": "debt"},
        {"name": "Barclays China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.2, "returns": 5.5, "category": "debt"},
        {"name": "Standard Chartered China Bond Fund", "type": "debt", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 4.3, "returns": 5.6, "category": "debt"},
        
        # Balanced Funds (10+ funds)
        {"name": "Vanguard China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.5, "returns": 10.5, "category": "balanced"},
        {"name": "Fidelity China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.8, "returns": 10.7, "category": "balanced"},
        {"name": "BlackRock China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.6, "returns": 10.6, "category": "balanced"},
        {"name": "HSBC China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.4, "returns": 10.4, "category": "balanced"},
        {"name": "JP Morgan China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.7, "returns": 10.6, "category": "balanced"},
        {"name": "Goldman Sachs China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.9, "returns": 10.8, "category": "balanced"},
        {"name": "Morgan Stanley China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.5, "returns": 10.5, "category": "balanced"},
        {"name": "UBS China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.6, "returns": 10.6, "category": "balanced"},
        {"name": "Deutsche China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.4, "returns": 10.4, "category": "balanced"},
        {"name": "Credit Suisse China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.8, "returns": 10.7, "category": "balanced"},
        {"name": "Barclays China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.5, "returns": 10.5, "category": "balanced"},
        {"name": "Standard Chartered China Balanced Fund", "type": "balanced", "currency": "USD", "geography": "China",
         "market_cap": None, "volatility": 13.7, "returns": 10.6, "category": "balanced"},
    ]
    
    all_funds = inr_funds + usd_usa_funds + usd_japan_funds + usd_india_funds + usd_europe_funds + usd_uk_funds + usd_china_funds
    
    # Generate historical returns data for each fund (5 years)
    for fund in all_funds:
        # Generate correlated returns based on volatility and expected returns
        np.random.seed(hash(fund["name"]) % 2**32)
        annual_return = fund["returns"] / 100
        annual_vol = fund["volatility"] / 100
        
        # Generate daily returns (assuming 252 trading days)
        daily_return = annual_return / 252
        daily_vol = annual_vol / np.sqrt(252)
        
        # Generate returns with some autocorrelation
        returns = np.random.normal(daily_return, daily_vol, len(dates))
        returns = pd.Series(returns, index=dates)
        
        # Calculate drawdown
        cumulative = (1 + returns).cumprod()
        running_max = cumulative.expanding().max()
        drawdown = (cumulative - running_max) / running_max
        max_drawdown = drawdown.min() * 100
        
        fund["returns_series"] = returns
        fund["max_drawdown"] = abs(max_drawdown)
        fund["sharpe_ratio"] = (annual_return - 0.03) / annual_vol if annual_vol > 0 else 0
        
        funds.append(fund)
    
    # Create DataFrame
    df = pd.DataFrame([
        {
            "name": f["name"],
            "type": f["type"],
            "currency": f["currency"],
            "geography": f["geography"],
            "market_cap": f["market_cap"],
            "volatility": f["volatility"],
            "returns": f["returns"],
            "category": f["category"],
            "max_drawdown": f["max_drawdown"],
            "sharpe_ratio": f["sharpe_ratio"],
            "returns_series": f["returns_series"]
        }
        for f in funds
    ])
    
    return df

def get_funds_by_criteria(df, currency, category=None, geography=None):
    """Filter funds by currency, category, and geography."""
    filtered = df[df["currency"] == currency]
    
    if category:
        filtered = filtered[filtered["category"] == category]
    
    if geography:
        filtered = filtered[filtered["geography"] == geography]
    
    return filtered
